name: Artifacts
run-name: ${{ github.actor }} -> ${{ github.event.head_commit.message }}
defaults:
  run:
    shell: bash ## shellキーでbashを指定しておくだけで、パイプラインの処理エラーを無視するのをやめさせることができる
on: push

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - run: date > date.txt # save artifact
      - uses: actions/upload-artifact@v4
        with:
          name: artifact-name
          path: date.txt # the path which you wanna upload.
          retention-days: 7 # period which Github saves this artifact. default is 90 days.
  download:
    runs-on: ubuntu-latest
    needs: [upload]
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: artifact-name
          path: download-dest-path # the destination of the directory which you wanna download into.
      - run: cat download-dest-path/date.txt

