name: Comment
on: push
run-name: Run by @${{ github.actor }}
jobs:
  comment:
    runs-on: ubuntu-latest
    permissions: # permission to the GITHUB_TOKEN
      pull-requests: write
      contents: read
    steps:
      - uses: actions/checkout@v4
      - run: gh pr comment "${GITHUB_HEAD_REF}" --body "Hello, ${GITHUB_ACTOR}!"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # credential for GITHUB CLI
      - run: echo "${GITHUB_HEAD_REF}"
        if: ${{ failure() }}
