name: workflow name
# コミットメッセージと実行者名を明示する
run-name: ${{ github.actor }} -> ${{ github.event.head_commit.message }}

# bashを使った実行による不便なところをなくすために、おまじないとして入れておく
defaults:
  run:
    shell: bash ## shellキーでbashを指定しておくだけで、パイプラインの処理エラーを無視するのをやめさせることができる

on: push

jobs:
  print:
    name: simple job # Jobの名前 ここには実行者名を入れることができない
    runs-on: ubuntu-latest
    steps:
      - name: simple step # 実行ステップの名前 ここには実行者名を入れることができない
        run: echo "hello"