name: Manual Matrix
# コミットメッセージと実行者名を明示する
run-name: ${{ github.actor }} -> ${{ github.event.head_commit.message }}

# bashを使った実行による不便なところをなくすために、おまじないとして入れておく
defaults:
  run:
    shell: bash ## shellキーでbashを指定しておくだけで、パイプラインの処理エラーを無視するのをやめさせることができる

on: push

jobs:
  print:
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            version: '3.10'
          - os: windows-latest
            version: '3.11'
          - os: macos-latest
            version: '3.12'
    runs-on: ${{matrix.os}}
    steps:
        - name: set up python ${{matrix.version}} on ${{matrix.os}}
          uses: actions/setup-python@v5
          with:
            python-version: ${{matrix.version}}
        - run: echo "${RUNNER_OS}"
        - run: python -v

