name: Old
run-name: ${{ github.actor }} -> ${{ github.event.head_commit.message }}
defaults:
  run:
    shell: bash
on: workflow_dispatch
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v4 # old ver.