name: secrets
on: push
jobs:
  print:
    runs-on: ubuntu-latest
    env:
      PASSWORD: ${{secrets.PASSWORD}}
    steps:
      - run: echo "password=${PASSWORD}"
      - run: echo "password=${PASSWORD:0:1} ${PASSWORD#?}"
